# Generated by Django 4.0.2 on 2022-02-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='state',
        ),
        migrations.RemoveField(
            model_name='light',
            name='state',
        ),
    ]
