# Generated by Django 4.0.2 on 2022-02-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0002_remove_group_state_remove_light_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='name',
            field=models.CharField(default='<django.db.models.fields.PositiveIntegerField>', max_length=16),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='<django.db.models.fields.PositiveIntegerField>', max_length=16),
        ),
    ]
