# Generated by Django 4.0.2 on 2022-02-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0003_light_name_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='lights',
            field=models.ManyToManyField(to='lights.Light'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='light',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
